Dev
MatthLC/P4_Tournament_manager pull request #2
Opened 2021-10-25 16:55 UTC by MatthLC

- restructuration du menu en "switch case"
- application de la pep8 avec flake8
- correction et finalisation de commande de l'application

2021-11-03 12:43 UTC, williamsko requested changes

2021-11-03 12:43 UTC, williamsko commented on .gitignore
> +venv
Trouve un moyen d'ignorer les fichiers .pyc

2021-11-03 12:43 UTC, williamsko commented on controllers/actor.py
> +    def show_all_actor(self):
je dirai plutôt `show_all_actors`

2021-11-03 12:43 UTC, williamsko commented on controllers/base.py
> +class Controller:
nommer cette classe `Controller` tout court me dérange un peu.  Mets un nom un peu plus significatif.

2021-11-03 12:43 UTC, williamsko commented on controllers/base.py
> +                            print("Il n'y pas de tournoi pour le moment.")
Tu as oublié ce `print` ?

2021-11-03 12:43 UTC, williamsko commented on controllers/base.py
> +                        print('Saisie incorrecte.')
apparends à utiliser les logs. mais je laisse passer pour le moment

2021-11-03 12:43 UTC, williamsko commented on controllers/menu_reporting.py
> +    def back_to_main_menu(self):
A quoi sert cette fonction du coup ?

2021-11-03 12:43 UTC, williamsko commented on controllers/tournament.py
> +            self.tournament.current_matches = SwissSystem().first_round(
J'aurais bien aimé que tu instancies  vraiment `SwissSystem ` avant d'appeler la méthode  `first_round `

2021-11-03 12:43 UTC, williamsko commented on controllers/tournament.py
> +            self.tournament.current_matches = SwissSystem().other_round(
Pareille remarque que plus haut

2021-11-03 12:43 UTC, williamsko commented on controllers/tournament.py
> +            last_name = self.actors_database.matable_df.loc[int(self.match[int(self.result) - 1])].first_name
Pour récupérer `first_name` et `last_name` tu fais le même calcul. Pourquoi ne fais-tu pas le calcul une seule fois ? Une fois que tu as l'objet, tu peux récupérer `first_name` et `last_name`

2021-11-03 12:43 UTC, williamsko commented on flake-report/back.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Tout ce qui se trouve dans le repertoire `flake_report` devrait être ignoré

2021-11-03 12:43 UTC, williamsko commented on models/player.py
> +class Players:
nope c'est la classe `Player` et non `Players`

2021-11-03 12:43 UTC, williamsko commented on readme.md
> +Ce projet est développé avec la version de Python 3.9.7, il est par conséquent recommandé d'installer cette version avant de continuer.
tu peux montrer comment on installe cette version ?

2021-11-03 12:43 UTC, williamsko commented on readme.md
> +`python -m venv venv`
Donne un autre nom autre que `venv stp`

2021-11-04 10:10 UTC, MatthLC commented on controllers/actor.py
> +    def show_all_actor(self):
corrigé

2021-11-04 10:11 UTC, MatthLC commented on controllers/base.py
> +class Controller:
renommée en TournamentManager

2021-11-04 10:13 UTC, MatthLC commented on controllers/base.py
> +                            print("Il n'y pas de tournoi pour le moment.")
utilisation de la méthode self.view.display

2021-11-04 10:14 UTC, MatthLC commented on controllers/menu_reporting.py
> +    def back_to_main_menu(self):
J'ai oublié de la supprimer

2021-11-04 10:25 UTC, MatthLC commented on controllers/tournament.py
> +            last_name = self.actors_database.matable_df.loc[int(self.match[int(self.result) - 1])].first_name
corrigé : récupération des informations du joueurs dans la variable "get_player_information" puis get_player_information.first_name ou last_name

2021-11-04 10:25 UTC, MatthLC commented on flake-report/back.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
ok

2021-11-04 10:31 UTC, MatthLC commented on models/player.py
> +class Players:
Ce model sera supprimé car non utilisé

2021-11-04 10:34 UTC, MatthLC commented on readme.md
> +`python -m venv venv`
renommé en tournament

2021-11-04 10:40 UTC, MatthLC commented on flake-report/back.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Mais c'est un livrable demandé sous GitHub, je le retire quand même ?

2021-11-04 16:36 UTC, MatthLC commented on readme.md
> +Ce projet est développé avec la version de Python 3.9.7, il est par conséquent recommandé d'installer cette version avant de continuer.
j'ai remplacé par 3.9

2021-11-05 17:00 UTC, merged